version: "3.8"
networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  mock-llm:
    image: python:3.11-slim
    cap_drop: 
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      lab-net:
        ipv4_address: 172.28.0.10

  juice-shop:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      lab-net:
        ipv4_address: 172.28.0.11

  elk:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      lab-net:
        ipv4_address: 172.28.0.12

  kibana:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      lab-net:
        ipv4_address: 172.28.0.13

  suricata:
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      lab-net:
        ipv4_address: 172.28.0.14

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.0
    user: root
    volumes:
      - ./zeek/logs:/usr/share/filebeat/logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - lab-net
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

